export interface ICryptocurrency {
  id: string;
  icon: string; // svg src
  symbol: string; // USDT
  name: string; // Tether
  decimals: number; // decimal places
  contract: string;
  fee: number;
  enableDeposit: boolean;
  enableWithdraw: boolean;
  enableTrade: boolean;
  enableMargin: boolean;
  createdAt: number;
  updatedAt: number;
}

export const dummyCryptocurrency: ICryptocurrency = {
  id: 'USDT',
  icon: '/asset_icon/usdt.svg',
  symbol: 'USDT',
  name: 'Tether',
  contract: '0x',
  decimals: 6,
  fee: 0,
  enableDeposit: false,
  enableWithdraw: false,
  enableTrade: false,
  enableMargin: false,
  createdAt: 0,
  updatedAt: 0,
};

export const dummyCryptocurrencies: ICryptocurrency[] = [
  {
    id: 'USDT',
    symbol: 'USDT',
    name: 'Tether',
    decimals: 6,
    icon: '/asset_icon/usdt.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'ETH',
    symbol: 'ETH',
    name: 'ETH',
    decimals: 18,
    icon: '/asset_icon/eth.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'BTC',
    symbol: 'BTC',
    name: 'BTC',
    decimals: 18,
    icon: '/asset_icon/btc.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'USDC',
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'DAI',
    symbol: 'DAI',
    name: 'DAI',
    decimals: 18,
    icon: '/asset_icon/dai.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'BNB',
    symbol: 'BNB',
    name: 'BNB',
    decimals: 18,
    icon: '/asset_icon/bnb.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'BCH',
    symbol: 'BCH',
    name: 'BCH',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'LTC',
    symbol: 'LTC',
    name: 'LTC',
    decimals: 18,
    icon: '/asset_icon/ltc.svg',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'ETC',
    symbol: 'ETC',
    name: 'ETC',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'USX',
    symbol: 'USX',
    name: 'USX',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'NEO',
    symbol: 'NEO',
    name: 'NEO',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'EOS',
    symbol: 'EOS',
    name: 'EOS',
    decimals: 18,
    icon: '',
    fee: 0,
    contract: '0x',
    enableDeposit: false,
    enableWithdraw: false,
    enableTrade: false,
    enableMargin: false,
    createdAt: 0,
    updatedAt: 0,
  },
];
