/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        "spacing-lv-13": "120px",
        "spacing-lv-12": "96px",
        "spacing-lv-11": "80px",
        "spacing-lv-10": "72px",
        "spacing-lv-9": "56px",
        "spacing-lv-8": "40px",
        "spacing-lv-7": "32px",
        "spacing-lv-6": "24px",
        "spacing-lv-5": "20px",
        "spacing-lv-4": "16px",
        "spacing-lv-3": "12px",
        "spacing-lv-2": "8px",
        "spacing-lv-1": "6px",
        "spacing-lv-0": "4px",
        "spacing-none": "0px",
      },
      colors: {
        "surface-neutral-background": "var(--neutral-light-grey-100)",
        "surface-neutral-container-lv1": "var(--neutral-light-grey-50)",
        "surface-neutral-container-lv2": "var(--neutral-light-grey-25)",
        "surface-neutral-container-lv3": "var(--neutral-white)",
        "surface-neutral-inverse": "var(--neutral-light-grey-800)",
        "surface-neutral-solid-white": "var(--neutral-white)",
        "surface-neutral-mask": "var(--neutral-light-grey-opacity-70)",
        "surface-neutral-mask-subtle": "var(--neutral-light-grey-opacity-16)",
        "surface-brand-primary-bright": "var(--primary-light-aqua-300)",
        "surface-brand-primary-default": "var(--primary-light-aqua-400)",
        "surface-state-error-bright": "var(--error-light-red-400)",
        "surface-brand-primary-dim": "var(--primary-light-aqua-600)",
        "surface-brand-primary-hover": "var(--primary-light-aqua-100)",
        "surface-brand-primary-container": "var(--primary-light-aqua-25)",
        "surface-brand-primary-container-hover": "var(--primary-light-aqua-50)",
        "surface-brand-secondary-bright": "var(--secondary-light-mint-300)",
        "surface-brand-secondary-default": "var(--secondary-light-mint-400)",
        "surface-brand-secondary-dim": "var(--secondary-light-mint-600)",
        "surface-brand-secondary-hover": "var(--secondary-light-mint-100)",
        "surface-brand-secondary-container": "var(--secondary-light-mint-25)",
        "surface-brand-secondary-container-hover":
          "var(--secondary-light-mint-50)",
        "surface-state-error": "var(--error-light-red-500)",
        "surface-state-error-strong": "var(--error-light-red-600)",
        "surface-state-error-hover": "var(--error-light-red-300)",
        "surface-state-error-container": "var(--error-light-red-25)",
        "surface-state-error-container-hover": "var(--error-light-red-50)",
        "surface-state-warning-bright": "var(--warning-light-yellow-400)",
        "surface-state-warning": "var(--warning-light-yellow-500)",
        "surface-state-warning-dim": "var(--warning-light-yellow-600)",
        "surface-state-warning-hover": "var(--warning-light-yellow-300)",
        "surface-state-warning-container": "var(--warning-light-yellow-25)",
        "surface-state-warning-container-hover":
          "var(--warning-light-yellow-50)",
        "surface-state-success-bright": "var(--success-light-green-400)",
        "surface-state-success": "var(--success-light-green-500)",
        "surface-state-success-dim": "var(--success-light-green-600)",
        "surface-state-success-hover": "var(--success-light-green-300)",
        "surface-state-success-container": "var(--success-light-green-25)",
        "surface-state-success-container-hover":
          "var(--success-light-green-50)",
        "surface-state-info-bright": "var(--info-light-blue-400)",
        "surface-state-info": "var(--info-light-blue-500)",
        "surface-state-info-dim": "var(--info-light-blue-600)",
        "surface-state-info-hover": "var(--info-light-blue-200)",
        "surface-state-info-container": "var(--info-light-blue-25)",
        "surface-state-info-container-hover": "var(--info-light-blue-50)",
        "surface-state-mute": "var(--neutral-light-grey-300)",
        "surface-state-mute-container": "var(--neutral-light-grey-200)",
        "text-neutral-primary": "var(--neutral-light-grey-800)",
        "text-neutral-secondary": "var(--neutral-light-grey-700)",
        "text-neutral-tertiary": "var(--neutral-light-grey-500)",
        "text-neutral-inverse": "var(--neutral-white)",
        "text-neutral-solid-light": "var(--neutral-white)",
        "text-neutral-solid-dark": "var(--neutral-light-grey-800)",
        "text-brand-primary": "var(--primary-light-aqua-600)",
        "text-brand-primary-hover": "var(--primary-light-aqua-500)",
        "text-brand-on-primary": "var(--primary-light-aqua-900)",
        "text-brand-on-primary-container": "var(--primary-light-aqua-700)",
        "text-brand-secondary": "var(--secondary-light-mint-600)",
        "text-brand-secondary-hover": "var(--secondary-light-mint-500)",
        "text-brand-on-secondary": "var(--secondary-light-mint-900)",
        "text-state-error": "var(--error-light-red-700)",
        "text-state-error-hover": "var(--error-light-red-600)",
        "text-state-on-error": "var(--neutral-white)",
        "text-state-on-error-container": "var(--error-light-red-700)",
        "text-brand-on-secondary-container": "var(--secondary-light-mint-700)",
        "text-state-warning": "var(--warning-light-yellow-800)",
        "text-state-warning-hover": "var(--warning-light-yellow-700)",
        "text-state-on-warning": "var(--warning-light-yellow-900)",
        "text-state-on-warning-container": "var(--warning-light-yellow-800)",
        "text-state-success": "var(--success-light-green-700)",
        "text-state-success-hover": "var(--success-light-green-600)",
        "text-state-on-success": "var(--neutral-white)",
        "text-state-on-success-container": "var(--success-light-green-700)",
        "text-state-info": "var(--info-light-blue-600)",
        "text-state-info-hover": "var(--info-light-blue-500)",
        "text-state-on-info": "var(--neutral-white)",
        "text-state-on-info-container": "var(--info-light-blue-700)",
        "text-state-mute": "var(--neutral-light-grey-300)",
        "text-state-on-mute": "var(--neutral-light-grey-500)",
        "text-state-on-mute-container": "var(--neutral-light-grey-300)",
        "border-neutral-subtle": "var(--neutral-light-grey-200)",
        "border-neutral-default": "var(--neutral-light-grey-300)",
        "border-brand-primary": "var(--primary-light-aqua-500)",
        "border-brand-primary-hover": "var(--primary-light-aqua-600)",
        "border-brand-on-primary": "var(--primary-light-aqua-600)",
        "border-brand-on-primary-hover": "var(--primary-light-aqua-700)",
        "border-brand-on-primary-container": "var(--primary-light-aqua-500)",
        "border-brand-on-primary-container-hover":
          "var(--primary-light-aqua-400)",
        "border-state-error": "var(--error-light-red-500)",
        "border-state-error-hover": "var(--error-light-red-400)",
        "border-state-on-error": "var(--error-light-red-900)",
        "border-state-on-error-hover": "var(--error-light-red-700)",
        "border-state-on-error-container": "var(--error-light-red-600)",
        "border-state-on-error-container-hover": "var(--error-light-red-500)",
        "border-state-warning": "var(--warning-light-yellow-800)",
        "border-state-warning-hover": "var(--warning-light-yellow-700)",
        "border-state-on-warning": "var(--warning-light-yellow-900)",
        "border-state-on-warning-hover": "var(--warning-light-yellow-800)",
        "border-state-on-warning-container": "var(--warning-light-yellow-800)",
        "border-state-on-warning-container-hover":
          "var(--warning-light-yellow-700)",
        "border-state-success": "var(--success-light-green-400)",
        "border-state-success-hover": "var(--success-light-green-200)",
        "border-state-on-success": "var(--success-light-green-700)",
        "border-state-on-success-hover": "var(--success-light-green-600)",
        "border-state-on-success-container": "var(--success-light-green-500)",
        "border-state-on-success-container-hover":
          "var(--success-light-green-300)",
        "border-state-info": "var(--info-light-blue-500)",
        "border-state-info-hover": "var(--info-light-blue-300)",
        "border-state-on-info": "var(--info-light-blue-700)",
        "border-state-on-info-hover": "var(--info-light-blue-600)",
        "border-state-on-info-container": "var(--info-light-blue-500)",
        "border-state-on-info-container-hover": "var(--info-light-blue-300)",
        "border-state-mute": "var(--neutral-light-grey-300)",
        "border-state-on-mute": "var(--neutral-light-grey-400)",
        "border-state-on-mute-container": "var(--neutral-light-grey-300)",
        "border-brand-secondary": "var(--secondary-light-mint-500)",
        "border-brand-secondary-hover": "var(--secondary-light-mint-400)",
        "border-brand-on-secondary": "var(--secondary-light-mint-600)",
        "border-brand-on-secondary-hover": "var(--secondary-light-mint-400)",
        "border-brand-on-secondary-container":
          "var(--secondary-light-mint-500)",
        "border-brand-on-secondary-container-hover":
          "var(--secondary-light-mint-300)",
        "border-neutral-strong": "var(--neutral-light-grey-400)",
        "border-neutral-hover": "var(--neutral-light-grey-600)",
        "border-neutral-contrast": "var(--neutral-light-grey-800)",
        "border-neutral-solid-white": "var(--neutral-light-grey-25)",
        "border-neutral-inverse": "var(--neutral-light-grey-25)",
        "icon-neutral-primary": "var(--neutral-light-grey-800)",
        "icon-neutral-secondary": "var(--neutral-light-grey-700)",
        "icon-neutral-tertiary": "var(--neutral-light-grey-400)",
        "icon-neutral-inverse": "var(--neutral-white)",
        "icon-neutral-solid-white": "var(--neutral-white)",
        "icon-brand-primary": "var(--primary-light-aqua-600)",
        "icon-brand-primary-hover": "var(--primary-light-aqua-400)",
        "icon-brand-on-primary-small": "var(--primary-light-aqua-900)",
        "icon-brand-on-primary-large": "var(--neutral-white)",
        "icon-brand-on-primary-container": "var(--primary-light-aqua-600)",
        "icon-brand-secondary": "var(--secondary-light-mint-600)",
        "icon-brand-secondary-hover": "var(--secondary-light-mint-400)",
        "icon-brand-on-secondary": "var(--secondary-light-mint-900)",
        "icon-brand-on-secondary-container": "var(--secondary-light-mint-700)",
        "icon-state-error": "var(--error-light-red-600)",
        "icon-state-error-hover": "var(--error-light-red-500)",
        "icon-state-on-error": "var(--neutral-white)",
        "icon-state-on-error-container": "var(--error-light-red-700)",
        "icon-state-warning": "var(--warning-light-yellow-700)",
        "icon-state-warning-hover": "var(--warning-light-yellow-600)",
        "icon-state-on-warning": "var(--warning-light-yellow-900)",
        "icon-state-on-warning-container": "var(--warning-light-yellow-800)",
        "icon-state-success": "var(--success-light-green-600)",
        "icon-state-success-hover": "var(--success-light-green-400)",
        "icon-state-on-success": "var(--neutral-white)",
        "icon-state-on-success-container": "var(--success-light-green-700)",
        "icon-state-info": "var(--info-light-blue-500)",
        "icon-state-info-hover": "var(--info-light-blue-300)",
        "icon-state-on-info": "var(--neutral-white)",
        "icon-state-on-info-container": "var(--info-light-blue-700)",
        "icon-state-mute": "var(--neutral-light-grey-400)",
        "icon-state-on-mute": "var(--neutral-light-grey-400)",
        "icon-state-on-mute-container": "var(--neutral-light-grey-300)",
        "icon-state-like-hover": "var(--error-light-red-25)",
        "opacity-brand-primary-8": "var(--primary-light-aqua-opacity-08)",
        "opacity-brand-primary-10": "var(--primary-light-aqua-opacity-10)",
        "opacity-brand-primary-16": "var(--primary-light-aqua-opacity-16)",
        "opacity-brand-secondary-8": "var(--secondary-light-mint-opacity-08)",
        "opacity-brand-secondary-10": "var(--secondary-light-mint-opacity-10)",
        "opacity-brand-secondary-16": "var(--secondary-light-mint-opacity-16)",
        "opacity-state-error-0": "var(--error-light-red-opacity-00)",
        "opacity-state-error-8": "var(--error-light-red-opacity-08)",
        "opacity-state-error-10": "var(--error-light-red-opacity-10)",
        "opacity-state-error-16": "var(--error-light-red-opacity-16)",
        "opacity-state-success-0": "var(--success-light-green-opacity-00)",
        "opacity-state-success-8": "var(--success-light-green-opacity-08)",
        "opacity-state-success-10": "var(--success-light-green-opacity-10)",
        "opacity-state-success-16": "var(--success-light-green-opacity-16)",
        "opacity-state-warn-8": "var(--warning-dark-yellow-opacity-08)",
        "opacity-state-warn-10": "var(--warning-light-yellow-opacity-10)",
        "opacity-state-warn-16": "var(--warning-light-yellow-opacity-16)",
        "opacity-state-info-8": "var(--info-light-blue-opacity-08)",
        "opacity-state-info-10": "var(--info-light-blue-opacity-10)",
        "opacity-state-info-16": "var(--info-light-blue-opacity-16)",
        "logo-gradient-0": "var(--primary-light-aqua-500)",
        "logo-gradient-100": "var(--secondary-light-mint-500)",
        "logo-light": "var(--neutral-light-grey-25)",
        "logo-dark": "var(--neutral-light-grey-800)",
        "logo-watermark": "var(--neutral-light-grey-opacity-16)",
        "illustration-red-900": "var(--error-light-red-900)",
        "illustration-red-800": "var(--error-light-red-800)",
        "illustration-red-700": "var(--error-light-red-700)",
        "illustration-red-600": "var(--error-light-red-600)",
        "illustration-red-500": "var(--error-light-red-500)",
        "illustration-red-400": "var(--error-light-red-400)",
        "illustration-red-300": "var(--error-light-red-300)",
        "illustration-red-200": "var(--error-light-red-200)",
        "illustration-red-100": "var(--error-light-red-100)",
        "illustration-red-50": "var(--error-light-red-50)",
        "illustration-red-25": "var(--error-light-red-25)",
        "illustration-aqua-900": "var(--primary-light-aqua-900)",
        "illustration-mint-900": "var(--secondary-light-mint-900)",
        "illustration-neutral-900": "var(--neutral-light-grey-900)",
        "illustration-neutral-800": "var(--neutral-light-grey-800)",
        "illustration-neutral-700": "var(--neutral-light-grey-700)",
        "illustration-neutral-600": "var(--neutral-light-grey-600)",
        "illustration-neutral-500": "var(--neutral-light-grey-500)",
        "illustration-neutral-400": "var(--neutral-light-grey-400)",
        "illustration-neutral-300": "var(--neutral-light-grey-300)",
        "illustration-neutral-200": "var(--neutral-light-grey-200)",
        "illustration-neutral-100": "var(--neutral-light-grey-100)",
        "illustration-neutral-50": "var(--neutral-light-grey-50)",
        "illustration-neutral-25": "var(--neutral-light-grey-25)",
        "illustration-mint-800": "var(--secondary-light-mint-800)",
        "illustration-mint-700": "var(--secondary-light-mint-700)",
        "illustration-mint-600": "var(--secondary-light-mint-600)",
        "illustration-mint-500": "var(--secondary-light-mint-500)",
        "illustration-mint-400": "var(--secondary-light-mint-400)",
        "illustration-mint-300": "var(--secondary-light-mint-300)",
        "illustration-mint-200": "var(--secondary-light-mint-200)",
        "illustration-mint-100": "var(--secondary-light-mint-100)",
        "illustration-mint-50": "var(--secondary-light-mint-50)",
        "illustration-mint-25": "var(--secondary-light-mint-25)",
        "illustration-aqua-800": "var(--primary-light-aqua-800)",
        "illustration-aqua-700": "var(--primary-light-aqua-700)",
        "illustration-aqua-600": "var(--primary-light-aqua-600)",
        "illustration-aqua-500": "var(--primary-light-aqua-500)",
        "illustration-aqua-400": "var(--primary-light-aqua-400)",
        "illustration-aqua-300": "var(--primary-light-aqua-300)",
        "illustration-aqua-200": "var(--primary-light-aqua-200)",
        "illustration-aqua-100": "var(--primary-light-aqua-100)",
        "illustration-aqua-50": "var(--primary-light-aqua-50)",
        "illustration-aqua-25": "var(--primary-light-aqua-25)",
      },
      borderRadius: {
        "radius-rounded": "999px",
        "radius-xl": "25px",
        "radius-l": "20px",
        "radius-m": "15px",
        "radius-s": "10px",
        "radius-xs": "5px",
        "radius-xxs": "3px",
      },
    },
  },
  plugins: [],
};
