/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'login-background': "url('/elements/login_background.png')",
      },
      colors: {
        'accordion-outline-active': 'var(--color-accordion-outline-active)',
        'accordion-outline-default': 'var(--color-accordion-outline-default)',
        'accordion-surface-background-active': 'var(--color-accordion-surface-background-active)',
        'accordion-surface-background-hover': 'var(--color-accordion-surface-background-hover)',
        'accordion-surface-background': 'var(--color-accordion-surface-background)',
        'accordion-surface-disable': 'var(--color-accordion-surface-disable)',
        'accordion-surface-indicator-active': 'var(--color-accordion-surface-indicator-active)',
        'accordion-surface-indicator': 'var(--color-accordion-surface-indicator)',
        'accordion-text-head': 'var(--color-accordion-text-head)',
        'accordion-text-note': 'var(--color-accordion-text-note)',
        'accordion-text-on-disable': 'var(--color-accordion-text-on-disable)',
        'accordion-text-on-indicator-active': 'var(--color-accordion-text-on-indicator-active)',
        'accordion-text-on-indicator': 'var(--color-accordion-text-on-indicator)',
        'accordion-text-paragraph': 'var(--color-accordion-text-paragraph)',
        'alert-surface-error': 'var(--color-alert-surface-error)',
        'alert-surface-icon-background': 'var(--color-alert-surface-icon-background)',
        'alert-surface-icon-error': 'var(--color-alert-surface-icon-error)',
        'alert-surface-icon-info': 'var(--color-alert-surface-icon-info)',
        'alert-surface-icon-success': 'var(--color-alert-surface-icon-success)',
        'alert-surface-icon-warn': 'var(--color-alert-surface-icon-warn)',
        'alert-surface-info': 'var(--color-alert-surface-info)',
        'alert-surface-success': 'var(--color-alert-surface-success)',
        'alert-surface-warn': 'var(--color-alert-surface-warn)',
        'alert-text-on-error': 'var(--color-alert-text-on-error)',
        'alert-text-on-info': 'var(--color-alert-text-on-info)',
        'alert-text-on-success': 'var(--color-alert-text-on-success)',
        'alert-text-on-warn': 'var(--color-alert-text-on-warn)',
        'avatar-outline-default': 'var(--color-avatar-outline-default)',
        'avatar-surface-baby': 'var(--color-avatar-surface-baby)',
        'avatar-surface-default': 'var(--color-avatar-surface-default)',
        'avatar-surface-indicator-neutral': 'var(--color-avatar-surface-indicator-neutral)',
        'avatar-surface-indicator-primary': 'var(--color-avatar-surface-indicator-primary)',
        'avatar-surface-indigo': 'var(--color-avatar-surface-indigo)',
        'avatar-surface-maple': 'var(--color-avatar-surface-maple)',
        'avatar-surface-olive': 'var(--color-avatar-surface-olive)',
        'avatar-surface-pink': 'var(--color-avatar-surface-pink)',
        'avatar-surface-placeholder': 'var(--color-avatar-surface-placeholder)',
        'avatar-surface-rose': 'var(--color-avatar-surface-rose)',
        'avatar-surface-taro': 'var(--color-avatar-surface-taro)',
        'avatar-text-on-base': 'var(--color-avatar-text-on-base)',
        'avatar-text-on-indicator': 'var(--color-avatar-text-on-indicator)',
        'badge-brand-on-primary-tonal': 'var(--color-badge-brand-on-primary-tonal)',
        'badge-brand-on-primary': 'var(--color-badge-brand-on-primary)',
        'badge-brand-on-secondary-tonal': 'var(--color-badge-brand-on-secondary-tonal)',
        'badge-brand-on-secondary': 'var(--color-badge-brand-on-secondary)',
        'badge-brand-primary-outline': 'var(--color-badge-brand-primary-outline)',
        'badge-brand-primary-tonal': 'var(--color-badge-brand-primary-tonal)',
        'badge-brand-primary': 'var(--color-badge-brand-primary)',
        'badge-brand-secondary-outline': 'var(--color-badge-brand-secondary-outline)',
        'badge-brand-secondary-tonal': 'var(--color-badge-brand-secondary-tonal)',
        'badge-brand-secondary': 'var(--color-badge-brand-secondary)',
        'badge-neutral-dark': 'var(--color-badge-neutral-dark)',
        'badge-neutral-light': 'var(--color-badge-neutral-light)',
        'badge-neutral-on-dark': 'var(--color-badge-neutral-on-dark)',
        'badge-neutral-on-light': 'var(--color-badge-neutral-on-light)',
        'badge-state-error-outline': 'var(--color-badge-state-error-outline)',
        'badge-state-error-tonal': 'var(--color-badge-state-error-tonal)',
        'badge-state-error': 'var(--color-badge-state-error)',
        'badge-state-info-outline': 'var(--color-badge-state-info-outline)',
        'badge-state-info-tonal': 'var(--color-badge-state-info-tonal)',
        'badge-state-info': 'var(--color-badge-state-info)',
        'badge-state-on-error-tonal': 'var(--color-badge-state-on-error-tonal)',
        'badge-state-on-error': 'var(--color-badge-state-on-error)',
        'badge-state-on-info-tonal': 'var(--color-badge-state-on-info-tonal)',
        'badge-state-on-info': 'var(--color-badge-state-on-info)',
        'badge-state-on-success-tonal': 'var(--color-badge-state-on-success-tonal)',
        'badge-state-on-success': 'var(--color-badge-state-on-success)',
        'badge-state-on-warn-tonal': 'var(--color-badge-state-on-warn-tonal)',
        'badge-state-on-warn': 'var(--color-badge-state-on-warn)',
        'badge-state-success-outline': 'var(--color-badge-state-success-outline)',
        'badge-state-success-tonal': 'var(--color-badge-state-success-tonal)',
        'badge-state-success': 'var(--color-badge-state-success)',
        'badge-state-warn-outline': 'var(--color-badge-state-warn-outline)',
        'badge-state-warn-tonal': 'var(--color-badge-state-warn-tonal)',
        'badge-state-warn': 'var(--color-badge-state-warn)',
        'border-brand-on-primary-container-hover':
          'var(--color-border-brand-on-primary-container-hover)',
        'border-brand-on-primary-container': 'var(--color-border-brand-on-primary-container)',
        'border-brand-on-primary-hover': 'var(--color-border-brand-on-primary-hover)',
        'border-brand-on-primary': 'var(--color-border-brand-on-primary)',
        'border-brand-on-secondary-container-hover':
          'var(--color-border-brand-on-secondary-container-hover)',
        'border-brand-on-secondary-container': 'var(--color-border-brand-on-secondary-container)',
        'border-brand-on-secondary-hover': 'var(--color-border-brand-on-secondary-hover)',
        'border-brand-on-secondary': 'var(--color-border-brand-on-secondary)',
        'border-brand-primary-hover': 'var(--color-border-brand-primary-hover)',
        'border-brand-primary': 'var(--color-border-brand-primary)',
        'border-brand-secondary-hover': 'var(--color-border-brand-secondary-hover)',
        'border-brand-secondary': 'var(--color-border-brand-secondary)',
        'border-neutral-contrast': 'var(--color-border-neutral-contrast)',
        'border-neutral-default': 'var(--color-border-neutral-default)',
        'border-neutral-hover': 'var(--color-border-neutral-hover)',
        'border-neutral-inverse': 'var(--color-border-neutral-inverse)',
        'border-neutral-solid-white': 'var(--color-border-neutral-solid-white)',
        'border-neutral-strong': 'var(--color-border-neutral-strong)',
        'border-neutral-subtle': 'var(--color-border-neutral-subtle)',
        'border-state-error-hover': 'var(--color-border-state-error-hover)',
        'border-state-error': 'var(--color-border-state-error)',
        'border-state-info-hover': 'var(--color-border-state-info-hover)',
        'border-state-info': 'var(--color-border-state-info)',
        'border-state-mute': 'var(--color-border-state-mute)',
        'border-state-on-error-container-hover':
          'var(--color-border-state-on-error-container-hover)',
        'border-state-on-error-container': 'var(--color-border-state-on-error-container)',
        'border-state-on-error-hover': 'var(--color-border-state-on-error-hover)',
        'border-state-on-error': 'var(--color-border-state-on-error)',
        'border-state-on-info-container-hover': 'var(--color-border-state-on-info-container-hover)',
        'border-state-on-info-container': 'var(--color-border-state-on-info-container)',
        'border-state-on-info-hover': 'var(--color-border-state-on-info-hover)',
        'border-state-on-info': 'var(--color-border-state-on-info)',
        'border-state-on-mute-container': 'var(--color-border-state-on-mute-container)',
        'border-state-on-mute': 'var(--color-border-state-on-mute)',
        'border-state-on-success-container-hover':
          'var(--color-border-state-on-success-container-hover)',
        'border-state-on-success-container': 'var(--color-border-state-on-success-container)',
        'border-state-on-success-hover': 'var(--color-border-state-on-success-hover)',
        'border-state-on-success': 'var(--color-border-state-on-success)',
        'border-state-on-warning-container-hover':
          'var(--color-border-state-on-warning-container-hover)',
        'border-state-on-warning-container': 'var(--color-border-state-on-warning-container)',
        'border-state-on-warning-hover': 'var(--color-border-state-on-warning-hover)',
        'border-state-on-warning': 'var(--color-border-state-on-warning)',
        'border-state-success-hover': 'var(--color-border-state-success-hover)',
        'border-state-success': 'var(--color-border-state-success)',
        'border-state-warning-hover': 'var(--color-border-state-warning-hover)',
        'border-state-warning': 'var(--color-border-state-warning)',
        'breadcrumb-outline-divider': 'var(--color-breadcrumb-outline-divider)',
        'breadcrumb-surface-hover': 'var(--color-breadcrumb-surface-hover)',
        'breadcrumb-text-current': 'var(--color-breadcrumb-text-current)',
        'breadcrumb-text-default': 'var(--color-breadcrumb-text-default)',
        'breadcrumb-text-on-hover': 'var(--color-breadcrumb-text-on-hover)',
        'button-brand-filled-on-primary-active':
          'var(--color-button-brand-filled-on-primary-active)',
        'button-brand-filled-on-primary-default':
          'var(--color-button-brand-filled-on-primary-default)',
        'button-brand-filled-on-primary-soft': 'var(--color-button-brand-filled-on-primary-soft)',
        'button-brand-filled-on-secondary-active':
          'var(--color-button-brand-filled-on-secondary-active)',
        'button-brand-filled-on-secondary-default':
          'var(--color-button-brand-filled-on-secondary-default)',
        'button-brand-filled-on-secondary-soft':
          'var(--color-button-brand-filled-on-secondary-soft)',
        'button-brand-filled-primary-active': 'var(--color-button-brand-filled-primary-active)',
        'button-brand-filled-primary-default': 'var(--color-button-brand-filled-primary-default)',
        'button-brand-filled-primary-hover': 'var(--color-button-brand-filled-primary-hover)',
        'button-brand-filled-primary-soft-hover':
          'var(--color-button-brand-filled-primary-soft-hover)',
        'button-brand-filled-primary-soft': 'var(--color-button-brand-filled-primary-soft)',
        'button-brand-filled-secondary-active': 'var(--color-button-brand-filled-secondary-active)',
        'button-brand-filled-secondary-default':
          'var(--color-button-brand-filled-secondary-default)',
        'button-brand-filled-secondary-hover': 'var(--color-button-brand-filled-secondary-hover)',
        'button-brand-filled-secondary-soft-hover':
          'var(--color-button-brand-filled-secondary-soft-hover)',
        'button-brand-filled-secondary-soft': 'var(--color-button-brand-filled-secondary-soft)',
        'button-brand-outline-on-primary-default':
          'var(--color-button-brand-outline-on-primary-default)',
        'button-brand-outline-on-primary-hover':
          'var(--color-button-brand-outline-on-primary-hover)',
        'button-brand-outline-on-secondary-default':
          'var(--color-button-brand-outline-on-secondary-default)',
        'button-brand-outline-on-secondary-hover':
          'var(--color-button-brand-outline-on-secondary-hover)',
        'button-brand-outline-primary-active-outline':
          'var(--color-button-brand-outline-primary-active-outline)',
        'button-brand-outline-primary-active-surface':
          'var(--color-button-brand-outline-primary-active-surface)',
        'button-brand-outline-primary-default': 'var(--color-button-brand-outline-primary-default)',
        'button-brand-outline-primary-hover-outline':
          'var(--color-button-brand-outline-primary-hover-outline)',
        'button-brand-outline-primary-hover-surface':
          'var(--color-button-brand-outline-primary-hover-surface)',
        'button-brand-outline-secondary-active-outline':
          'var(--color-button-brand-outline-secondary-active-outline)',
        'button-brand-outline-secondary-active-surface':
          'var(--color-button-brand-outline-secondary-active-surface)',
        'button-brand-outline-secondary-default':
          'var(--color-button-brand-outline-secondary-default)',
        'button-brand-outline-secondary-hover-outline':
          'var(--color-button-brand-outline-secondary-hover-outline)',
        'button-brand-outline-secondary-hover-surface':
          'var(--color-button-brand-outline-secondary-hover-surface)',
        'button-neutral-filled-neutral-active': 'var(--color-button-neutral-filled-neutral-active)',
        'button-neutral-filled-neutral-default':
          'var(--color-button-neutral-filled-neutral-default)',
        'button-neutral-filled-neutral-hover': 'var(--color-button-neutral-filled-neutral-hover)',
        'button-neutral-filled-on-neutral-active':
          'var(--color-button-neutral-filled-on-neutral-active)',
        'button-neutral-filled-on-neutral-default':
          'var(--color-button-neutral-filled-on-neutral-default)',
        'button-neutral-filled-on-neutral-hover':
          'var(--color-button-neutral-filled-on-neutral-hover)',
        'button-neutral-outline-neutral-active-outline':
          'var(--color-button-neutral-outline-neutral-active-outline)',
        'button-neutral-outline-neutral-default':
          'var(--color-button-neutral-outline-neutral-default)',
        'button-neutral-outline-neutral-hover-outline':
          'var(--color-button-neutral-outline-neutral-hover-outline)',
        'button-neutral-outline-on-neutral-default':
          'var(--color-button-neutral-outline-on-neutral-default)',
        'button-neutral-outline-on-neutral-hover':
          'var(--color-button-neutral-outline-on-neutral-hover)',
        'button-neutral-segment-active-outline':
          'var(--color-button-neutral-segment-active-outline)',
        'button-neutral-segment-active-surface':
          'var(--color-button-neutral-segment-active-surface)',
        'button-neutral-segment-default-outline':
          'var(--color-button-neutral-segment-default-outline)',
        'button-neutral-segment-default-surface':
          'var(--color-button-neutral-segment-default-surface)',
        'button-neutral-segment-disable-outline':
          'var(--color-button-neutral-segment-disable-outline)',
        'button-neutral-segment-disable-surface':
          'var(--color-button-neutral-segment-disable-surface)',
        'button-neutral-segment-hover-outline': 'var(--color-button-neutral-segment-hover-outline)',
        'button-neutral-segment-hover-surface': 'var(--color-button-neutral-segment-hover-surface)',
        'button-neutral-segment-on-active': 'var(--color-button-neutral-segment-on-active)',
        'button-neutral-segment-on-default': 'var(--color-button-neutral-segment-on-default)',
        'button-neutral-segment-on-disable': 'var(--color-button-neutral-segment-on-disable)',
        'button-neutral-segment-on-hover-2': 'var(--color-button-neutral-segment-on-hover-2)',
        'button-neutral-segment-on-hover': 'var(--color-button-neutral-segment-on-hover)',
        'button-state-filled-disable': 'var(--color-button-state-filled-disable)',
        'button-state-filled-error-active': 'var(--color-button-state-filled-error-active)',
        'button-state-filled-error-default': 'var(--color-button-state-filled-error-default)',
        'button-state-filled-error-hover': 'var(--color-button-state-filled-error-hover)',
        'button-state-filled-error-soft-hover': 'var(--color-button-state-filled-error-soft-hover)',
        'button-state-filled-error-soft': 'var(--color-button-state-filled-error-soft)',
        'button-state-filled-info-active': 'var(--color-button-state-filled-info-active)',
        'button-state-filled-info-default': 'var(--color-button-state-filled-info-default)',
        'button-state-filled-info-hover': 'var(--color-button-state-filled-info-hover)',
        'button-state-filled-info-soft-hover': 'var(--color-button-state-filled-info-soft-hover)',
        'button-state-filled-info-soft': 'var(--color-button-state-filled-info-soft)',
        'button-state-filled-on-disable': 'var(--color-button-state-filled-on-disable)',
        'button-state-filled-on-error-active': 'var(--color-button-state-filled-on-error-active)',
        'button-state-filled-on-error-default': 'var(--color-button-state-filled-on-error-default)',
        'button-state-filled-on-error-soft': 'var(--color-button-state-filled-on-error-soft)',
        'button-state-filled-on-info-active': 'var(--color-button-state-filled-on-info-active)',
        'button-state-filled-on-info-default': 'var(--color-button-state-filled-on-info-default)',
        'button-state-filled-on-info-hover': 'var(--color-button-state-filled-on-info-hover)',
        'button-state-filled-on-info-soft': 'var(--color-button-state-filled-on-info-soft)',
        'button-state-filled-on-success-active':
          'var(--color-button-state-filled-on-success-active)',
        'button-state-filled-on-success-default':
          'var(--color-button-state-filled-on-success-default)',
        'button-state-filled-on-success-soft': 'var(--color-button-state-filled-on-success-soft)',
        'button-state-filled-on-warn-active': 'var(--color-button-state-filled-on-warn-active)',
        'button-state-filled-on-warn-default': 'var(--color-button-state-filled-on-warn-default)',
        'button-state-filled-on-warn-soft': 'var(--color-button-state-filled-on-warn-soft)',
        'button-state-filled-success-active': 'var(--color-button-state-filled-success-active)',
        'button-state-filled-success-default': 'var(--color-button-state-filled-success-default)',
        'button-state-filled-success-hover': 'var(--color-button-state-filled-success-hover)',
        'button-state-filled-success-soft-hover':
          'var(--color-button-state-filled-success-soft-hover)',
        'button-state-filled-success-soft': 'var(--color-button-state-filled-success-soft)',
        'button-state-filled-warn-active': 'var(--color-button-state-filled-warn-active)',
        'button-state-filled-warn-default': 'var(--color-button-state-filled-warn-default)',
        'button-state-filled-warn-hover': 'var(--color-button-state-filled-warn-hover)',
        'button-state-filled-warn-soft-hover': 'var(--color-button-state-filled-warn-soft-hover)',
        'button-state-filled-warn-soft': 'var(--color-button-state-filled-warn-soft)',
        'button-state-outline-disable': 'var(--color-button-state-outline-disable)',
        'button-state-outline-error-active-outline':
          'var(--color-button-state-outline-error-active-outline)',
        'button-state-outline-error-active-surface':
          'var(--color-button-state-outline-error-active-surface)',
        'button-state-outline-error-default': 'var(--color-button-state-outline-error-default)',
        'button-state-outline-error-hover-outline':
          'var(--color-button-state-outline-error-hover-outline)',
        'button-state-outline-error-hover-surface':
          'var(--color-button-state-outline-error-hover-surface)',
        'button-state-outline-info-active-outline':
          'var(--color-button-state-outline-info-active-outline)',
        'button-state-outline-info-active-surface':
          'var(--color-button-state-outline-info-active-surface)',
        'button-state-outline-info-default': 'var(--color-button-state-outline-info-default)',
        'button-state-outline-info-hover-outline':
          'var(--color-button-state-outline-info-hover-outline)',
        'button-state-outline-info-hover-surface':
          'var(--color-button-state-outline-info-hover-surface)',
        'button-state-outline-on-disable': 'var(--color-button-state-outline-on-disable)',
        'button-state-outline-on-error-default':
          'var(--color-button-state-outline-on-error-default)',
        'button-state-outline-on-error-hover': 'var(--color-button-state-outline-on-error-hover)',
        'button-state-outline-on-info-default': 'var(--color-button-state-outline-on-info-default)',
        'button-state-outline-on-info-hover': 'var(--color-button-state-outline-on-info-hover)',
        'button-state-outline-on-success-default':
          'var(--color-button-state-outline-on-success-default)',
        'button-state-outline-on-success-hover':
          'var(--color-button-state-outline-on-success-hover)',
        'button-state-outline-on-warn-default': 'var(--color-button-state-outline-on-warn-default)',
        'button-state-outline-on-warn-hover': 'var(--color-button-state-outline-on-warn-hover)',
        'button-state-outline-success-active-outline':
          'var(--color-button-state-outline-success-active-outline)',
        'button-state-outline-success-active-surface':
          'var(--color-button-state-outline-success-active-surface)',
        'button-state-outline-success-default': 'var(--color-button-state-outline-success-default)',
        'button-state-outline-success-hover-outline':
          'var(--color-button-state-outline-success-hover-outline)',
        'button-state-outline-success-hover-surface':
          'var(--color-button-state-outline-success-hover-surface)',
        'button-state-outline-warn-active-outline':
          'var(--color-button-state-outline-warn-active-outline)',
        'button-state-outline-warn-active-surface':
          'var(--color-button-state-outline-warn-active-surface)',
        'button-state-outline-warn-default': 'var(--color-button-state-outline-warn-default)',
        'button-state-outline-warn-hover-outline':
          'var(--color-button-state-outline-warn-hover-outline)',
        'button-state-outline-warn-hover-surface':
          'var(--color-button-state-outline-warn-hover-surface)',
        'button-toggle-active-primary': 'var(--color-button-toggle-active-primary)',
        'button-toggle-active': 'var(--color-button-toggle-active)',
        'button-toggle-default-primary': 'var(--color-button-toggle-default-primary)',
        'button-toggle-default': 'var(--color-button-toggle-default)',
        'button-toggle-fav-hover': 'var(--color-button-toggle-fav-hover)',
        'button-toggle-fav-on': 'var(--color-button-toggle-fav-on)',
        'button-toggle-fav-outline': 'var(--color-button-toggle-fav-outline)',
        'button-toggle-hover': 'var(--color-button-toggle-hover)',
        'button-toggle-like-hover': 'var(--color-button-toggle-like-hover)',
        'button-toggle-like-on': 'var(--color-button-toggle-like-on)',
        'button-toggle-like-outline': 'var(--color-button-toggle-like-outline)',
        'button-toggle-thumb-hover': 'var(--color-button-toggle-thumb-hover)',
        'button-toggle-thumb-on-blue': 'var(--color-button-toggle-thumb-on-blue)',
        'button-toggle-thumb-on-white': 'var(--color-button-toggle-thumb-on-white)',
        'button-toggle-thumb-outline': 'var(--color-button-toggle-thumb-outline)',
        'calendar-outline-picker-divider': 'var(--color-calendar-outline-picker-divider)',
        'calendar-outline-picker-outline': 'var(--color-calendar-outline-picker-outline)',
        'calendar-surface-calendar': 'var(--color-calendar-surface-calendar)',
        'calendar-surface-picker-active': 'var(--color-calendar-surface-picker-active)',
        'calendar-surface-picker-hover': 'var(--color-calendar-surface-picker-hover)',
        'calendar-surface-picker-period': 'var(--color-calendar-surface-picker-period)',
        'calendar-text-picker--period': 'var(--color-calendar-text-picker--period)',
        'calendar-text-picker-active': 'var(--color-calendar-text-picker-active)',
        'calendar-text-picker-disable': 'var(--color-calendar-text-picker-disable)',
        'calendar-text-picker-hover': 'var(--color-calendar-text-picker-hover)',
        'calendar-text-picker-primary': 'var(--color-calendar-text-picker-primary)',
        'calendar-text-picker-secondary': 'var(--color-calendar-text-picker-secondary)',
        'card-surface-bg-secondary': 'var(--color-card-surface-bg-secondary)',
        'card-surface-lv-1': 'var(--color-card-surface-lv-1)',
        'card-surface-lv-2': 'var(--color-card-surface-lv-2)',
        'card-surface-lv-3': 'var(--color-card-surface-lv-3)',
        'card-surface-primary': 'var(--color-card-surface-primary)',
        'card-text-primary': 'var(--color-card-text-primary)',
        'card-text-secondary': 'var(--color-card-text-secondary)',
        'card-text-tertiary': 'var(--color-card-text-tertiary)',
        'card-text-text-white': 'var(--color-card-text-text-white)',
        'carousel-indicator-active': 'var(--color-carousel-indicator-active)',
        'carousel-indicator-base': 'var(--color-carousel-indicator-base)',
        'carousel-nav-hover': 'var(--color-carousel-nav-hover)',
        'carousel-nav': 'var(--color-carousel-nav)',
        'chart-outline-down': 'var(--color-chart-outline-down)',
        'chart-outline-up': 'var(--color-chart-outline-up)',
        'chart-surface-down-0': 'var(--color-chart-surface-down-0)',
        'chart-surface-down-16': 'var(--color-chart-surface-down-16)',
        'chart-surface-up-0': 'var(--color-chart-surface-up-0)',
        'chart-surface-up-16': 'var(--color-chart-surface-up-16)',
        'chatbubble-surface-primary': 'var(--color-chatbubble-surface-primary)',
        'chatbubble-surface-secondary': 'var(--color-chatbubble-surface-secondary)',
        'chatbubble-text-error': 'var(--color-chatbubble-text-error)',
        'chatbubble-text-note': 'var(--color-chatbubble-text-note)',
        'chatbubble-text-on-primary': 'var(--color-chatbubble-text-on-primary)',
        'chatbubble-text-on-secondary': 'var(--color-chatbubble-text-on-secondary)',
        'chatbubble-text-read-active': 'var(--color-chatbubble-text-read-active)',
        'chatbubble-text-read-default': 'var(--color-chatbubble-text-read-default)',
        'checkbox-outline-active-outline': 'var(--color-checkbox-outline-active-outline)',
        'checkbox-outline-hover': 'var(--color-checkbox-outline-hover)',
        'checkbox-outline-unselected-error': 'var(--color-checkbox-outline-unselected-error)',
        'checkbox-outline-unselected': 'var(--color-checkbox-outline-unselected)',
        'checkbox-surface-active-error': 'var(--color-checkbox-surface-active-error)',
        'checkbox-surface-active': 'var(--color-checkbox-surface-active)',
        'checkbox-surface-disable': 'var(--color-checkbox-surface-disable)',
        'checkbox-surface-focus': 'var(--color-checkbox-surface-focus)',
        'checkbox-surface-hover': 'var(--color-checkbox-surface-hover)',
        'checkbox-surface-unselected-error': 'var(--color-checkbox-surface-unselected-error)',
        'checkbox-surface-unselected': 'var(--color-checkbox-surface-unselected)',
        'checkbox-text-error': 'var(--color-checkbox-text-error)',
        'checkbox-text-label': 'var(--color-checkbox-text-label)',
        'checkbox-text-note': 'var(--color-checkbox-text-note)',
        'checkbox-text-on-active-error': 'var(--color-checkbox-text-on-active-error)',
        'checkbox-text-on-active': 'var(--color-checkbox-text-on-active)',
        'checkbox-text-on-disable': 'var(--color-checkbox-text-on-disable)',
        'divider-contrast': 'var(--color-divider-contrast)',
        'divider-default': 'var(--color-divider-default)',
        'divider-label': 'var(--color-divider-label)',
        'divider-strong': 'var(--color-divider-strong)',
        'divider-subtle': 'var(--color-divider-subtle)',
        'dropdown-surface-active': 'var(--color-dropdown-surface-active)',
        'dropdown-surface-base': 'var(--color-dropdown-surface-base)',
        'dropdown-surface-disable': 'var(--color-dropdown-surface-disable)',
        'dropdown-surface-hover': 'var(--color-dropdown-surface-hover)',
        'dropdown-text-disable': 'var(--color-dropdown-text-disable)',
        'icon-brand-on-primary-container': 'var(--color-icon-brand-on-primary-container)',
        'icon-brand-on-primary-large': 'var(--color-icon-brand-on-primary-large)',
        'icon-brand-on-primary-small': 'var(--color-icon-brand-on-primary-small)',
        'icon-brand-on-secondary-container': 'var(--color-icon-brand-on-secondary-container)',
        'icon-brand-on-secondary': 'var(--color-icon-brand-on-secondary)',
        'icon-brand-primary-hover': 'var(--color-icon-brand-primary-hover)',
        'icon-brand-primary': 'var(--color-icon-brand-primary)',
        'icon-brand-secondary-hover': 'var(--color-icon-brand-secondary-hover)',
        'icon-brand-secondary': 'var(--color-icon-brand-secondary)',
        'icon-neutral-inverse': 'var(--color-icon-neutral-inverse)',
        'icon-neutral-primary': 'var(--color-icon-neutral-primary)',
        'icon-neutral-secondary': 'var(--color-icon-neutral-secondary)',
        'icon-neutral-solid-white': 'var(--color-icon-neutral-solid-white)',
        'icon-neutral-tertiary': 'var(--color-icon-neutral-tertiary)',
        'icon-state-error-hover': 'var(--color-icon-state-error-hover)',
        'icon-state-error': 'var(--color-icon-state-error)',
        'icon-state-info-hover': 'var(--color-icon-state-info-hover)',
        'icon-state-info': 'var(--color-icon-state-info)',
        'icon-state-like-hover': 'var(--color-icon-state-like-hover)',
        'icon-state-mute': 'var(--color-icon-state-mute)',
        'icon-state-on-error-container': 'var(--color-icon-state-on-error-container)',
        'icon-state-on-error': 'var(--color-icon-state-on-error)',
        'icon-state-on-info-container': 'var(--color-icon-state-on-info-container)',
        'icon-state-on-info': 'var(--color-icon-state-on-info)',
        'icon-state-on-mute-container': 'var(--color-icon-state-on-mute-container)',
        'icon-state-on-mute': 'var(--color-icon-state-on-mute)',
        'icon-state-on-success-container': 'var(--color-icon-state-on-success-container)',
        'icon-state-on-success': 'var(--color-icon-state-on-success)',
        'icon-state-on-warning-container': 'var(--color-icon-state-on-warning-container)',
        'icon-state-on-warning': 'var(--color-icon-state-on-warning)',
        'icon-state-success-hover': 'var(--color-icon-state-success-hover)',
        'icon-state-success': 'var(--color-icon-state-success)',
        'icon-state-warning-hover': 'var(--color-icon-state-warning-hover)',
        'icon-state-warning': 'var(--color-icon-state-warning)',
        'illustration-aqua-100': 'var(--color-illustration-aqua-100)',
        'illustration-aqua-200': 'var(--color-illustration-aqua-200)',
        'illustration-aqua-25': 'var(--color-illustration-aqua-25)',
        'illustration-aqua-300': 'var(--color-illustration-aqua-300)',
        'illustration-aqua-400': 'var(--color-illustration-aqua-400)',
        'illustration-aqua-50': 'var(--color-illustration-aqua-50)',
        'illustration-aqua-500': 'var(--color-illustration-aqua-500)',
        'illustration-aqua-600': 'var(--color-illustration-aqua-600)',
        'illustration-aqua-700': 'var(--color-illustration-aqua-700)',
        'illustration-aqua-800': 'var(--color-illustration-aqua-800)',
        'illustration-aqua-900': 'var(--color-illustration-aqua-900)',
        'illustration-mint-100': 'var(--color-illustration-mint-100)',
        'illustration-mint-200': 'var(--color-illustration-mint-200)',
        'illustration-mint-25': 'var(--color-illustration-mint-25)',
        'illustration-mint-300': 'var(--color-illustration-mint-300)',
        'illustration-mint-400': 'var(--color-illustration-mint-400)',
        'illustration-mint-50': 'var(--color-illustration-mint-50)',
        'illustration-mint-500': 'var(--color-illustration-mint-500)',
        'illustration-mint-600': 'var(--color-illustration-mint-600)',
        'illustration-mint-700': 'var(--color-illustration-mint-700)',
        'illustration-mint-800': 'var(--color-illustration-mint-800)',
        'illustration-mint-900': 'var(--color-illustration-mint-900)',
        'illustration-neutral-100': 'var(--color-illustration-neutral-100)',
        'illustration-neutral-200': 'var(--color-illustration-neutral-200)',
        'illustration-neutral-25': 'var(--color-illustration-neutral-25)',
        'illustration-neutral-300': 'var(--color-illustration-neutral-300)',
        'illustration-neutral-400': 'var(--color-illustration-neutral-400)',
        'illustration-neutral-50': 'var(--color-illustration-neutral-50)',
        'illustration-neutral-500': 'var(--color-illustration-neutral-500)',
        'illustration-neutral-600': 'var(--color-illustration-neutral-600)',
        'illustration-neutral-700': 'var(--color-illustration-neutral-700)',
        'illustration-neutral-800': 'var(--color-illustration-neutral-800)',
        'illustration-neutral-900': 'var(--color-illustration-neutral-900)',
        'illustration-red-100': 'var(--color-illustration-red-100)',
        'illustration-red-200': 'var(--color-illustration-red-200)',
        'illustration-red-25': 'var(--color-illustration-red-25)',
        'illustration-red-300': 'var(--color-illustration-red-300)',
        'illustration-red-400': 'var(--color-illustration-red-400)',
        'illustration-red-50': 'var(--color-illustration-red-50)',
        'illustration-red-500': 'var(--color-illustration-red-500)',
        'illustration-red-600': 'var(--color-illustration-red-600)',
        'illustration-red-700': 'var(--color-illustration-red-700)',
        'illustration-red-800': 'var(--color-illustration-red-800)',
        'illustration-red-900': 'var(--color-illustration-red-900)',
        'indicator-notification': 'var(--color-indicator-notification)',
        'indicator-on-notification': 'var(--color-indicator-on-notification)',
        'indicator-scroll-bar': 'var(--color-indicator-scroll-bar)',
        'link-default': 'var(--color-link-default)',
        'link-disable': 'var(--color-link-disable)',
        'link-hover': 'var(--color-link-hover)',
        'loading-indicator-outline-default': 'var(--color-loading-indicator-outline-default)',
        'loading-indicator-surface-base': 'var(--color-loading-indicator-surface-base)',
        'loading-indicator-surface-error': 'var(--color-loading-indicator-surface-error)',
        'loading-indicator-surface-gradient-0': 'var(--color-loading-indicator-surface-gradient-0)',
        'loading-indicator-surface-gradient-100':
          'var(--color-loading-indicator-surface-gradient-100)',
        'loading-indicator-surface-primary': 'var(--color-loading-indicator-surface-primary)',
        'loading-indicator-surface-success': 'var(--color-loading-indicator-surface-success)',
        'loading-indicator-text-on-error': 'var(--color-loading-indicator-text-on-error)',
        'loading-indicator-text-on-gradient': 'var(--color-loading-indicator-text-on-gradient)',
        'loading-indicator-text-on-primary': 'var(--color-loading-indicator-text-on-primary)',
        'loading-indicator-text-on-success': 'var(--color-loading-indicator-text-on-success)',
        'loading-indicator-text-primary': 'var(--color-loading-indicator-text-primary)',
        'loading-indicator-text-secondary': 'var(--color-loading-indicator-text-secondary)',
        'logo-dark': 'var(--color-logo-dark)',
        'logo-gradient-0': 'var(--color-logo-gradient-0)',
        'logo-gradient-100': 'var(--color-logo-gradient-100)',
        'logo-light': 'var(--color-logo-light)',
        'logo-watermark': 'var(--color-logo-watermark)',
        'modal-surface-background': 'var(--color-modal-surface-background)',
        'modal-surface-close-button': 'var(--color-modal-surface-close-button)',
        'modal-text-paragraph': 'var(--color-modal-text-paragraph)',
        'modal-text-title': 'var(--color-modal-text-title)',
        'navigation-surface-active': 'var(--color-navigation-surface-active)',
        'navigation-surface-background': 'var(--color-navigation-surface-background)',
        'navigation-surface-hover': 'var(--color-navigation-surface-hover)',
        'navigation-surface-icon-active': 'var(--color-navigation-surface-icon-active)',
        'navigation-surface-icon-default': 'var(--color-navigation-surface-icon-default)',
        'navigation-surface-icon-disable': 'var(--color-navigation-surface-icon-disable)',
        'navigation-surface-icon-hover': 'var(--color-navigation-surface-icon-hover)',
        'navigation-text-active': 'var(--color-navigation-text-active)',
        'navigation-text-default': 'var(--color-navigation-text-default)',
        'navigation-text-disable': 'var(--color-navigation-text-disable)',
        'navigation-text-hover': 'var(--color-navigation-text-hover)',
        'opacity-brand-primary-10': 'var(--color-opacity-brand-primary-10)',
        'opacity-brand-primary-16': 'var(--color-opacity-brand-primary-16)',
        'opacity-brand-primary-8': 'var(--color-opacity-brand-primary-8)',
        'opacity-brand-secondary-10': 'var(--color-opacity-brand-secondary-10)',
        'opacity-brand-secondary-16': 'var(--color-opacity-brand-secondary-16)',
        'opacity-brand-secondary-8': 'var(--color-opacity-brand-secondary-8)',
        'opacity-neutral-lv2-0': 'var(--color-opacity-neutral-lv2-0)',
        'opacity-neutral-lv2-25': 'var(--color-opacity-neutral-lv2-25)',
        'opacity-neutral-lv2-50': 'var(--color-opacity-neutral-lv2-50)',
        'opacity-neutral-dark-80': 'var(--color-opacity-neutral-dark-80)',
        'opacity-state-error-0': 'var(--color-opacity-state-error-0)',
        'opacity-state-error-10': 'var(--color-opacity-state-error-10)',
        'opacity-state-error-16': 'var(--color-opacity-state-error-16)',
        'opacity-state-error-8': 'var(--color-opacity-state-error-8)',
        'opacity-state-info-10': 'var(--color-opacity-state-info-10)',
        'opacity-state-info-16': 'var(--color-opacity-state-info-16)',
        'opacity-state-info-8': 'var(--color-opacity-state-info-8)',
        'opacity-state-success-0': 'var(--color-opacity-state-success-0)',
        'opacity-state-success-10': 'var(--color-opacity-state-success-10)',
        'opacity-state-success-16': 'var(--color-opacity-state-success-16)',
        'opacity-state-success-8': 'var(--color-opacity-state-success-8)',
        'opacity-state-warn-10': 'var(--color-opacity-state-warn-10)',
        'opacity-state-warn-16': 'var(--color-opacity-state-warn-16)',
        'opacity-state-warn-8': 'var(--color-opacity-state-warn-8)',
        'pagination-active': 'var(--color-pagination-active)',
        'pagination-hover': 'var(--color-pagination-hover)',
        'pagination-text-active': 'var(--color-pagination-text-active)',
        'pagination-text-default': 'var(--color-pagination-text-default)',
        'pagination-text-disable': 'var(--color-pagination-text-disable)',
        'pagination-text-hover': 'var(--color-pagination-text-hover)',
        'radio-outline-active-outline': 'var(--color-radio-outline-active-outline)',
        'radio-outline-hover': 'var(--color-radio-outline-hover)',
        'radio-outline-unselected-error': 'var(--color-radio-outline-unselected-error)',
        'radio-outline-unselected': 'var(--color-radio-outline-unselected)',
        'radio-surface-active-error': 'var(--color-radio-surface-active-error)',
        'radio-surface-active': 'var(--color-radio-surface-active)',
        'radio-surface-disable': 'var(--color-radio-surface-disable)',
        'radio-surface-focus': 'var(--color-radio-surface-focus)',
        'radio-surface-hover': 'var(--color-radio-surface-hover)',
        'radio-surface-unselected-error': 'var(--color-radio-surface-unselected-error)',
        'radio-surface-unselected': 'var(--color-radio-surface-unselected)',
        'radio-text-error': 'var(--color-radio-text-error)',
        'radio-text-label': 'var(--color-radio-text-label)',
        'radio-text-note': 'var(--color-radio-text-note)',
        'radio-text-on-active-error': 'var(--color-radio-text-on-active-error)',
        'radio-text-on-active': 'var(--color-radio-text-on-active)',
        'radio-text-on-disable': 'var(--color-radio-text-on-disable)',
        'select-outline-active': 'var(--color-select-outline-active)',
        'select-outline-default': 'var(--color-select-outline-default)',
        'select-surface-active': 'var(--color-select-surface-active)',
        'select-surface-default': 'var(--color-select-surface-default)',
        'select-surface-disable': 'var(--color-select-surface-disable)',
        'select-text-active': 'var(--color-select-text-active)',
        'select-text-default': 'var(--color-select-text-default)',
        'select-text-disable': 'var(--color-select-text-disable)',
        'select-text-note': 'var(--color-select-text-note)',
        'skeleton-surface-base': 'var(--color-skeleton-surface-base)',
        'skeleton-surface-flash': 'var(--color-skeleton-surface-flash)',
        'slider-outline-active': 'var(--color-slider-outline-active)',
        'slider-surface-active': 'var(--color-slider-surface-active)',
        'slider-surface-base': 'var(--color-slider-surface-base)',
        'slider-surface-control': 'var(--color-slider-surface-control)',
        'slider-text-primary': 'var(--color-slider-text-primary)',
        'stepper-outline-process': 'var(--color-stepper-outline-process)',
        'stepper-outline-waiting': 'var(--color-stepper-outline-waiting)',
        'stepper-surface-error': 'var(--color-stepper-surface-error)',
        'stepper-surface-finish': 'var(--color-stepper-surface-finish)',
        'stepper-surface-process': 'var(--color-stepper-surface-process)',
        'stepper-surface-waiting': 'var(--color-stepper-surface-waiting)',
        'stepper-text-error': 'var(--color-stepper-text-error)',
        'stepper-text-note': 'var(--text-neutral-tertiary)',
        'stepper-text-on-finish': 'var(--color-stepper-text-on-finish)',
        'stepper-text-on-process': 'var(--color-stepper-text-on-process)',
        'stepper-text-on-waiting-container': 'var(--color-stepper-text-on-waiting-container)',
        'stepper-text-primary': 'var(--color-stepper-text-primary)',
        'stepper-text-process': 'var(--color-stepper-text-process)',
        'stepper-text-waiting': 'var(--color-stepper-text-waiting)',
        'surface-brand-primary-bright': 'var(--color-surface-brand-primary-bright)',
        'surface-brand-primary-container-hover':
          'var(--color-surface-brand-primary-container-hover)',
        'surface-brand-primary-container': 'var(--color-surface-brand-primary-container)',
        'surface-brand-primary-default': 'var(--color-surface-brand-primary-default)',
        'surface-brand-primary-dim': 'var(--color-surface-brand-primary-dim)',
        'surface-brand-primary-hover': 'var(--color-surface-brand-primary-hover)',
        'surface-brand-secondary-bright': 'var(--color-surface-brand-secondary-bright)',
        'surface-brand-secondary-container-hover':
          'var(--color-surface-brand-secondary-container-hover)',
        'surface-brand-secondary-container': 'var(--color-surface-brand-secondary-container)',
        'surface-brand-secondary-default': 'var(--color-surface-brand-secondary-default)',
        'surface-brand-secondary-dim': 'var(--color-surface-brand-secondary-dim)',
        'surface-brand-secondary-hover': 'var(--color-surface-brand-secondary-hover)',
        'surface-neutral-background': 'var(--color-surface-neutral-background)',
        'surface-neutral-container-lv1': 'var(--color-surface-neutral-container-lv1)',
        'surface-neutral-container-lv2': 'var(--color-surface-neutral-container-lv2)',
        'surface-neutral-container-lv3': 'var(--color-surface-neutral-container-lv3)',
        'surface-neutral-inverse': 'var(--color-surface-neutral-inverse)',
        'surface-neutral-mask-subtle': 'var(--color-surface-neutral-mask-subtle)',
        'surface-neutral-mask': 'var(--color-surface-neutral-mask)',
        'surface-neutral-solid-white': 'var(--color-surface-neutral-solid-white)',
        'surface-state-error-bright': 'var(--color-surface-state-error-bright)',
        'surface-state-error-container-hover': 'var(--color-surface-state-error-container-hover)',
        'surface-state-error-container': 'var(--color-surface-state-error-container)',
        'surface-state-error-hover': 'var(--color-surface-state-error-hover)',
        'surface-state-error-strong': 'var(--color-surface-state-error-strong)',
        'surface-state-error': 'var(--color-surface-state-error)',
        'surface-state-info-bright': 'var(--color-surface-state-info-bright)',
        'surface-state-info-container-hover': 'var(--color-surface-state-info-container-hover)',
        'surface-state-info-container': 'var(--color-surface-state-info-container)',
        'surface-state-info-dim': 'var(--color-surface-state-info-dim)',
        'surface-state-info-hover': 'var(--color-surface-state-info-hover)',
        'surface-state-info': 'var(--color-surface-state-info)',
        'surface-state-mute-container': 'var(--color-surface-state-mute-container)',
        'surface-state-mute': 'var(--color-surface-state-mute)',
        'surface-state-success-bright': 'var(--color-surface-state-success-bright)',
        'surface-state-success-container-hover':
          'var(--color-surface-state-success-container-hover)',
        'surface-state-success-container': 'var(--color-surface-state-success-container)',
        'surface-state-success-dim': 'var(--color-surface-state-success-dim)',
        'surface-state-success-hover': 'var(--color-surface-state-success-hover)',
        'surface-state-success': 'var(--color-surface-state-success)',
        'surface-state-warning-bright': 'var(--color-surface-state-warning-bright)',
        'surface-state-warning-container-hover':
          'var(--color-surface-state-warning-container-hover)',
        'surface-state-warning-container': 'var(--color-surface-state-warning-container)',
        'surface-state-warning-dim': 'var(--color-surface-state-warning-dim)',
        'surface-state-warning-hover': 'var(--color-surface-state-warning-hover)',
        'surface-state-warning': 'var(--color-surface-state-warning)',
        'switch-outline-process': 'var(--color-switch-outline-process)',
        'switch-outline-waiting': 'var(--color-switch-outline-waiting)',
        'switch-surface-active-default': 'var(--color-switch-surface-active-default)',
        'switch-surface-active-subtle': 'var(--color-switch-surface-active-subtle)',
        'switch-surface-base': 'var(--color-switch-surface-base)',
        'switch-surface-control-active': 'var(--color-switch-surface-control-active)',
        'switch-surface-control-default': 'var(--color-switch-surface-control-default)',
        'switch-surface-control-disable': 'var(--color-switch-surface-control-disable)',
        'switch-surface-disable': 'var(--color-switch-surface-disable)',
        'switch-text-disable': 'var(--color-switch-text-disable)',
        'switch-text-note': 'var(--color-switch-text-note)',
        'switch-text-primary': 'var(--color-switch-text-primary)',
        'table-outline-default': 'var(--color-table-outline-default)',
        'table-surface-default': 'var(--color-table-surface-default)',
        'table-surface-hover': 'var(--color-table-surface-hover)',
        'table-text-green': 'var(--color-table-text-green)',
        'table-text-primary': 'var(--color-table-text-primary)',
        'table-text-red': 'var(--color-table-text-red)',
        'table-text-support': 'var(--color-table-text-support)',
        'table-text-title-active': 'var(--color-table-text-title-active)',
        'table-text-title-default': 'var(--color-table-text-title-default)',
        'tabs-outline-active': 'var(--color-tabs-outline-active)',
        'tabs-outline-default': 'var(--color-tabs-outline-default)',
        'tabs-outline-disable': 'var(--color-tabs-outline-disable)',
        'tabs-outline-hover-neutral': 'var(--color-tabs-outline-hover-neutral)',
        'tabs-outline-hover-primary': 'var(--color-tabs-outline-hover-primary)',
        'tabs-surface-active-neutral': 'var(--color-tabs-surface-active-neutral)',
        'tabs-surface-active-primary': 'var(--color-tabs-surface-active-primary)',
        'tabs-surface-default': 'var(--color-tabs-surface-default)',
        'tabs-surface-disable': 'var(--color-tabs-surface-disable)',
        'tabs-surface-hover-neutral': 'var(--color-tabs-surface-hover-neutral)',
        'tabs-surface-hover-primary': 'var(--color-tabs-surface-hover-primary)',
        'tabs-text-active-neutral': 'var(--color-tabs-text-active-neutral)',
        'tabs-text-active-on-primary': 'var(--color-tabs-text-active-on-primary)',
        'tabs-text-active-primary': 'var(--color-tabs-text-active-primary)',
        'tabs-text-default': 'var(--color-tabs-text-default)',
        'tabs-text-disable': 'var(--color-tabs-text-disable)',
        'tabs-text-hove-neutral': 'var(--color-tabs-text-hove-neutral)',
        'tabs-text-hover-primary': 'var(--color-tabs-text-hover-primary)',
        'text-brand-on-primary-container': 'var(--color-text-brand-on-primary-container)',
        'text-brand-on-primary': 'var(--color-text-brand-on-primary)',
        'text-brand-on-secondary-container': 'var(--color-text-brand-on-secondary-container)',
        'text-brand-on-secondary': 'var(--color-text-brand-on-secondary)',
        'text-brand-primary-hover': 'var(--color-text-brand-primary-hover)',
        'text-brand-primary': 'var(--color-text-brand-primary)',
        'text-brand-secondary-hover': 'var(--color-text-brand-secondary-hover)',
        'text-brand-secondary': 'var(--color-text-brand-secondary)',
        'text-field-outline-default': 'var(--color-text-field-outline-default)',
        'text-field-outline-error': 'var(--color-text-field-outline-error)',
        'text-field-outline-focused': 'var(--color-text-field-outline-focused)',
        'text-field-outline-success': 'var(--color-text-field-outline-success)',
        'text-field-outline-warning': 'var(--color-text-field-outline-warning)',
        'text-field-surface-addon': 'var(--color-text-field-surface-addon)',
        'text-field-surface-default': 'var(--color-text-field-surface-default)',
        'text-field-surface-disable': 'var(--color-text-field-surface-disable)',
        'text-field-text-active': 'var(--color-text-field-text-active)',
        'text-field-text-disable': 'var(--color-text-field-text-disable)',
        'text-field-text-error': 'var(--color-text-field-text-error)',
        'text-field-text-label': 'var(--color-text-field-text-label)',
        'text-field-text-note': 'var(--color-text-field-text-note)',
        'text-field-text-placeholder': 'var(--color-text-field-text-placeholder)',
        'text-field-text-success': 'var(--color-text-field-text-success)',
        'text-field-text-warning': 'var(--color-text-field-text-warning)',
        'text-neutral-inverse': 'var(--color-text-neutral-inverse)',
        'text-neutral-primary': 'var(--color-text-neutral-primary)',
        'text-neutral-secondary': 'var(--color-text-neutral-secondary)',
        'text-neutral-solid-dark': 'var(--color-text-neutral-solid-dark)',
        'text-neutral-solid-light': 'var(--color-text-neutral-solid-light)',
        'text-neutral-tertiary': 'var(--color-text-neutral-tertiary)',
        'text-state-error-hover': 'var(--color-text-state-error-hover)',
        'text-state-error': 'var(--color-text-state-error)',
        'text-state-info-hover': 'var(--color-text-state-info-hover)',
        'text-state-info': 'var(--color-text-state-info)',
        'text-state-mute': 'var(--color-text-state-mute)',
        'text-state-on-error-container': 'var(--color-text-state-on-error-container)',
        'text-state-on-error': 'var(--color-text-state-on-error)',
        'text-state-on-info-container': 'var(--color-text-state-on-info-container)',
        'text-state-on-info': 'var(--color-text-state-on-info)',
        'text-state-on-mute-container': 'var(--color-text-state-on-mute-container)',
        'text-state-on-mute': 'var(--color-text-state-on-mute)',
        'text-state-on-success-container': 'var(--color-text-state-on-success-container)',
        'text-state-on-success': 'var(--color-text-state-on-success)',
        'text-state-on-warning-container': 'var(--color-text-state-on-warning-container)',
        'text-state-on-warning': 'var(--color-text-state-on-warning)',
        'text-state-success-hover': 'var(--color-text-state-success-hover)',
        'text-state-success': 'var(--color-text-state-success)',
        'text-state-warning-hover': 'var(--color-text-state-warning-hover)',
        'text-state-warning': 'var(--color-text-state-warning)',
        'tooltips-surface-default': 'var(--color-tooltips-surface-default)',
        'tooltips-surface-icon': 'var(--color-tooltips-surface-icon)',
        'tooltips-surface-inverse': 'var(--color-tooltips-surface-inverse)',
        'tooltips-text-default-primary': 'var(--color-tooltips-text-default-primary)',
        'tooltips-text-default-secondary': 'var(--color-tooltips-text-default-secondary)',
        'tooltips-text-inverse-primary': 'var(--color-tooltips-text-inverse-primary)',
        'tooltips-text-inverse-secondary': 'var(--color-tooltips-text-inverse-secondary)',
      },
      borderRadius: {
        'radius-rounded': 'var(--radius-rounded)',
        'radius-xl': 'var(--radius-xl)',
        'radius-l': 'var(--radius-l)',
        'radius-m': 'var(--radius-m)',
        'radius-s': 'var(--radius-s)',
        'radius-xs': 'var(--radius-xs)',
        'radius-xxs': 'var(--radius-xxs)',
      },
      spacing: {
        'spacing-lv-13': 'var(--spacing-lv-13)',
        'spacing-lv-12': 'var(--spacing-lv-12)',
        'spacing-lv-11': 'var(--spacing-lv-11)',
        'spacing-lv-10': 'var(--spacing-lv-10)',
        'spacing-lv-9': 'var(--spacing-lv-9)',
        'spacing-lv-8': 'var(--spacing-lv-8)',
        'spacing-lv-7': 'var(--spacing-lv-7)',
        'spacing-lv-6': 'var(--spacing-lv-6)',
        'spacing-lv-5': 'var(--spacing-lv-5)',
        'spacing-lv-4': 'var(--spacing-lv-4)',
        'spacing-lv-3': 'var(--spacing-lv-3)',
        'spacing-lv-2': 'var(--spacing-lv-2)',
        'spacing-lv-1': 'var(--spacing-lv-1)',
        'spacing-lv-0': 'var(--spacing-lv-0)',
        'spacing-none': 'var(--spacing-none)',

        '4px': '4px',
        '8px': '8px',
        '15px': '15px',
        '16px': '16px',
        '30px': '30px',
        '36px': '36px',
        '50px': '50px',
        '100px': '100px',
        '120px': '120px',
        '150px': '150px',
        '180px': '180px',
        '200px': '200px',
        '220px': '220px',
        '250px': '250px',
        '300px': '300px',
        '400px': '400px',
        '450px': '450px',
        '500px': '500px',
      },
      zIndex: {
        sidebar: 5000,
        masking: 10000,
        'masking-2': 20000,
        'lock-screen': 100000,
      },
    },
  },
  plugins: [],
};
