/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        "spacing-lv-13": "var(--spacing-lv-13)",
        "spacing-lv-12": "var(--spacing-lv-12)",
        "spacing-lv-11": "var(--spacing-lv-11)",
        "spacing-lv-10": "var(--spacing-lv-10)",
        "spacing-lv-9": "var(--spacing-lv-9)",
        "spacing-lv-8": "var(--spacing-lv-8)",
        "spacing-lv-7": "var(--spacing-lv-7)",
        "spacing-lv-6": "var(--spacing-lv-6)",
        "spacing-lv-5": "var(--spacing-lv-5)",
        "spacing-lv-4": "var(--spacing-lv-4)",
        "spacing-lv-3": "var(--spacing-lv-3)",
        "spacing-lv-2": "var(--spacing-lv-2)",
        "spacing-lv-1": "var(--spacing-lv-1)",
        "spacing-lv-0": "var(--spacing-lv-0)",
        "spacing-none": "var(--spacing-none)",
      },
      colors: {
        "surface-neutral-background": "var(--surface-neutral-background)",
        "surface-neutral-container-lv1": "var(--surface-neutral-container-lv1)",
        "surface-neutral-container-lv2": "var(--surface-neutral-container-lv2)",
        "surface-neutral-container-lv3": "var(--surface-neutral-container-lv3)",
        "surface-neutral-inverse": "var(--surface-neutral-inverse)",
        "surface-neutral-solid-white": "var(--surface-neutral-solid-white)",
        "surface-neutral-mask": "var(--surface-neutral-mask)",
        "surface-neutral-mask-subtle": "var(--surface-neutral-mask-subtle)",
        "surface-brand-primary-bright": "var(--surface-brand-primary-bright)",
        "surface-brand-primary-default": "var(--surface-brand-primary-default)",
        "surface-state-error-bright": "var(--surface-state-error-bright)",
        "surface-brand-primary-dim": "var(--surface-brand-primary-dim)",
        "surface-brand-primary-hover": "var(--surface-brand-primary-hover)",
        "surface-brand-primary-container":
          "var(--surface-brand-primary-container)",
        "surface-brand-primary-container-hover":
          "var(--surface-brand-primary-container-hover)",
        "surface-brand-secondary-bright":
          "var(--surface-brand-secondary-bright)",
        "surface-brand-secondary-default":
          "var(--surface-brand-secondary-default)",
        "surface-brand-secondary-dim": "var(--surface-brand-secondary-dim)",
        "surface-brand-secondary-hover": "var(--surface-brand-secondary-hover)",
        "surface-brand-secondary-container":
          "var(--surface-brand-secondary-container)",
        "surface-brand-secondary-container-hover":
          "var(--surface-brand-secondary-container-hover)",
        "surface-state-error": "var(--surface-state-error)",
        "surface-state-error-strong": "var(--surface-state-error-strong)",
        "surface-state-error-hover": "var(--surface-state-error-hover)",
        "surface-state-error-container": "var(--surface-state-error-container)",
        "surface-state-error-container-hover":
          "var(--surface-state-error-container-hover)",
        "surface-state-warning-bright": "var(--surface-state-warning-bright)",
        "surface-state-warning": "var(--surface-state-warning)",
        "surface-state-warning-dim": "var(--surface-state-warning-dim)",
        "surface-state-warning-hover": "var(--surface-state-warning-hover)",
        "surface-state-warning-container":
          "var(--surface-state-warning-container)",
        "surface-state-warning-container-hover":
          "var(--surface-state-warning-container-hover)",
        "surface-state-success-bright": "var(--surface-state-success-bright)",
        "surface-state-success": "var(--surface-state-success)",
        "surface-state-success-dim": "var(--surface-state-success-dim)",
        "surface-state-success-hover": "var(--surface-state-success-hover)",
        "surface-state-success-container":
          "var(--surface-state-success-container)",
        "surface-state-success-container-hover":
          "var(--surface-state-success-container-hover)",
        "surface-state-info-bright": "var(--surface-state-info-bright)",
        "surface-state-info": "var(--surface-state-info)",
        "surface-state-info-dim": "var(--surface-state-info-dim)",
        "surface-state-info-hover": "var(--surface-state-info-hover)",
        "surface-state-info-container": "var(--surface-state-info-container)",
        "surface-state-info-container-hover":
          "var(--surface-state-info-container-hover)",
        "surface-state-mute": "var(--surface-state-mute)",
        "surface-state-mute-container": "var(--surface-state-mute-container)",
        "text-neutral-primary": "var(--text-neutral-primary)",
        "text-neutral-secondary": "var(--text-neutral-secondary)",
        "text-neutral-tertiary": "var(--text-neutral-tertiary)",
        "text-neutral-inverse": "var(--text-neutral-inverse)",
        "text-neutral-solid-light": "var(--text-neutral-solid-light)",
        "text-neutral-solid-dark": "var(--text-neutral-solid-dark)",
        "text-brand-primary": "var(--text-brand-primary)",
        "text-brand-primary-hover": "var(--text-brand-primary-hover)",
        "text-brand-on-primary": "var(--text-brand-on-primary)",
        "text-brand-on-primary-container":
          "var(--text-brand-on-primary-container)",
        "text-brand-secondary": "var(--text-brand-secondary)",
        "text-brand-secondary-hover": "var(--text-brand-secondary-hover)",
        "text-brand-on-secondary": "var(--text-brand-on-secondary)",
        "text-state-error": "var(--text-state-error)",
        "text-state-error-hover": "var(--text-state-error-hover)",
        "text-state-on-error": "var(--text-state-on-error)",
        "text-state-on-error-container": "var(--text-state-on-error-container)",
        "text-brand-on-secondary-container":
          "var(--text-brand-on-secondary-container)",
        "text-state-warning": "var(--text-state-warning)",
        "text-state-warning-hover": "var(--text-state-warning-hover)",
        "text-state-on-warning": "var(--text-state-on-warning)",
        "text-state-on-warning-container":
          "var(--text-state-on-warning-container)",
        "text-state-success": "var(--text-state-success)",
        "text-state-success-hover": "var(--text-state-success-hover)",
        "text-state-on-success": "var(--text-state-on-success)",
        "text-state-on-success-container":
          "var(--text-state-on-success-container)",
        "text-state-info": "var(--text-state-info)",
        "text-state-info-hover": "var(--text-state-info-hover)",
        "text-state-on-info": "var(--text-state-on-info)",
        "text-state-on-info-container": "var(--text-state-on-info-container)",
        "text-state-mute": "var(--text-state-mute)",
        "text-state-on-mute": "var(--text-state-on-mute)",
        "text-state-on-mute-container": "var(--text-state-on-mute-container)",
        "border-neutral-subtle": "var(--border-neutral-subtle)",
        "border-neutral-default": "var(--border-neutral-default)",
        "border-brand-primary": "var(--border-brand-primary)",
        "border-brand-primary-hover": "var(--border-brand-primary-hover)",
        "border-brand-on-primary": "var(--border-brand-on-primary)",
        "border-brand-on-primary-hover": "var(--border-brand-on-primary-hover)",
        "border-brand-on-primary-container":
          "var(--border-brand-on-primary-container)",
        "border-brand-on-primary-container-hover":
          "var(--border-brand-on-primary-container-hover)",
        "border-state-error": "var(--border-state-error)",
        "border-state-error-hover": "var(--border-state-error-hover)",
        "border-state-on-error": "var(--border-state-on-error)",
        "border-state-on-error-hover": "var(--border-state-on-error-hover)",
        "border-state-on-error-container":
          "var(--border-state-on-error-container)",
        "border-state-on-error-container-hover":
          "var(--border-state-on-error-container-hover)",
        "border-state-warning": "var(--border-state-warning)",
        "border-state-warning-hover": "var(--border-state-warning-hover)",
        "border-state-on-warning": "var(--border-state-on-warning)",
        "border-state-on-warning-hover": "var(--border-state-on-warning-hover)",
        "border-state-on-warning-container":
          "var(--border-state-on-warning-container)",
        "border-state-on-warning-container-hover":
          "var(--border-state-on-warning-container-hover)",
        "border-state-success": "var(--border-state-success)",
        "border-state-success-hover": "var(--border-state-success-hover)",
        "border-state-on-success": "var(--border-state-on-success)",
        "border-state-on-success-hover": "var(--border-state-on-success-hover)",
        "border-state-on-success-container":
          "var(--border-state-on-success-container)",
        "border-state-on-success-container-hover":
          "var(--border-state-on-success-container-hover)",
        "border-state-info": "var(--border-state-info)",
        "border-state-info-hover": "var(--border-state-info-hover)",
        "border-state-on-info": "var(--border-state-on-info)",
        "border-state-on-info-hover": "var(--border-state-on-info-hover)",
        "border-state-on-info-container":
          "var(--border-state-on-info-container)",
        "border-state-on-info-container-hover":
          "var(--border-state-on-info-container-hover)",
        "border-state-mute": "var(--border-state-mute)",
        "border-state-on-mute": "var(--border-state-on-mute)",
        "border-state-on-mute-container":
          "var(--border-state-on-mute-container)",
        "border-brand-secondary": "var(--border-brand-secondary)",
        "border-brand-secondary-hover": "var(--border-brand-secondary-hover)",
        "border-brand-on-secondary": "var(--border-brand-on-secondary)",
        "border-brand-on-secondary-hover":
          "var(--border-brand-on-secondary-hover)",
        "border-brand-on-secondary-container":
          "var(--border-brand-on-secondary-container)",
        "border-brand-on-secondary-container-hover":
          "var(--border-brand-on-secondary-container-hover)",
        "border-neutral-strong": "var(--border-neutral-strong)",
        "border-neutral-hover": "var(--border-neutral-hover)",
        "border-neutral-contrast": "var(--border-neutral-contrast)",
        "border-neutral-solid-white": "var(--border-neutral-solid-white)",
        "border-neutral-inverse": "var(--border-neutral-inverse)",
        "icon-neutral-primary": "var(--icon-neutral-primary)",
        "icon-neutral-secondary": "var(--icon-neutral-secondary)",
        "icon-neutral-tertiary": "var(--icon-neutral-tertiary)",
        "icon-neutral-inverse": "var(--icon-neutral-inverse)",
        "icon-neutral-solid-white": "var(--icon-neutral-solid-white)",
        "icon-brand-primary": "var(--icon-brand-primary)",
        "icon-brand-primary-hover": "var(--icon-brand-primary-hover)",
        "icon-brand-on-primary-small": "var(--icon-brand-on-primary-small)",
        "icon-brand-on-primary-large": "var(--icon-brand-on-primary-large)",
        "icon-brand-on-primary-container":
          "var(--icon-brand-on-primary-container)",
        "icon-brand-secondary": "var(--icon-brand-secondary)",
        "icon-brand-secondary-hover": "var(--icon-brand-secondary-hover)",
        "icon-brand-on-secondary": "var(--icon-brand-on-secondary)",
        "icon-brand-on-secondary-container":
          "var(--icon-brand-on-secondary-container)",
        "icon-state-error": "var(--icon-state-error)",
        "icon-state-error-hover": "var(--icon-state-error-hover)",
        "icon-state-on-error": "var(--icon-state-on-error)",
        "icon-state-on-error-container": "var(--icon-state-on-error-container)",
        "icon-state-warning": "var(--icon-state-warning)",
        "icon-state-warning-hover": "var(--icon-state-warning-hover)",
        "icon-state-on-warning": "var(--icon-state-on-warning)",
        "icon-state-on-warning-container":
          "var(--icon-state-on-warning-container)",
        "icon-state-success": "var(--icon-state-success)",
        "icon-state-success-hover": "var(--icon-state-success-hover)",
        "icon-state-on-success": "var(--icon-state-on-success)",
        "icon-state-on-success-container":
          "var(--icon-state-on-success-container)",
        "icon-state-info": "var(--icon-state-info)",
        "icon-state-info-hover": "var(--icon-state-info-hover)",
        "icon-state-on-info": "var(--icon-state-on-info)",
        "icon-state-on-info-container": "var(--icon-state-on-info-container)",
        "icon-state-mute": "var(--icon-state-mute)",
        "icon-state-on-mute": "var(--icon-state-on-mute)",
        "icon-state-on-mute-container": "var(--icon-state-on-mute-container)",
        "icon-state-like-hover": "var(--icon-state-like-hover)",
        "opacity-brand-primary-8": "var(--opacity-brand-primary-8)",
        "opacity-brand-primary-10": "var(--opacity-brand-primary-10)",
        "opacity-brand-primary-16": "var(--opacity-brand-primary-16)",
        "opacity-brand-secondary-8": "var(--opacity-brand-secondary-8)",
        "opacity-brand-secondary-10": "var(--opacity-brand-secondary-10)",
        "opacity-brand-secondary-16": "var(--opacity-brand-secondary-16)",
        "opacity-state-error-0": "var(--opacity-state-error-0)",
        "opacity-state-error-8": "var(--opacity-state-error-8)",
        "opacity-state-error-10": "var(--opacity-state-error-10)",
        "opacity-state-error-16": "var(--opacity-state-error-16)",
        "opacity-state-success-0": "var(--opacity-state-success-0)",
        "opacity-state-success-8": "var(--opacity-state-success-8)",
        "opacity-state-success-10": "var(--opacity-state-success-10)",
        "opacity-state-success-16": "var(--opacity-state-success-16)",
        "opacity-state-warn-8": "var(--opacity-state-warn-8)",
        "opacity-state-warn-10": "var(--opacity-state-warn-10)",
        "opacity-state-warn-16": "var(--opacity-state-warn-16)",
        "opacity-state-info-8": "var(--opacity-state-info-8)",
        "opacity-state-info-10": "var(--opacity-state-info-10)",
        "opacity-state-info-16": "var(--opacity-state-info-16)",
        "logo-gradient-0": "var(--logo-gradient-0)",
        "logo-gradient-100": "var(--logo-gradient-100)",
        "logo-light": "var(--logo-light)",
        "logo-dark": "var(--logo-dark)",
        "logo-watermark": "var(--logo-watermark)",
        "illustration-red-900": "var(--illustration-red-900)",
        "illustration-red-800": "var(--illustration-red-800)",
        "illustration-red-700": "var(--illustration-red-700)",
        "illustration-red-600": "var(--illustration-red-600)",
        "illustration-red-500": "var(--illustration-red-500)",
        "illustration-red-400": "var(--illustration-red-400)",
        "illustration-red-300": "var(--illustration-red-300)",
        "illustration-red-200": "var(--illustration-red-200)",
        "illustration-red-100": "var(--illustration-red-100)",
        "illustration-red-50": "var(--illustration-red-50)",
        "illustration-red-25": "var(--illustration-red-25)",
        "illustration-aqua-900": "var(--illustration-aqua-900)",
        "illustration-mint-900": "var(--illustration-mint-900)",
        "illustration-neutral-900": "var(--illustration-neutral-900)",
        "illustration-neutral-800": "var(--illustration-neutral-800)",
        "illustration-neutral-700": "var(--illustration-neutral-700)",
        "illustration-neutral-600": "var(--illustration-neutral-600)",
        "illustration-neutral-500": "var(--illustration-neutral-500)",
        "illustration-neutral-400": "var(--illustration-neutral-400)",
        "illustration-neutral-300": "var(--illustration-neutral-300)",
        "illustration-neutral-200": "var(--illustration-neutral-200)",
        "illustration-neutral-100": "var(--illustration-neutral-100)",
        "illustration-neutral-50": "var(--illustration-neutral-50)",
        "illustration-neutral-25": "var(--illustration-neutral-25)",
        "illustration-mint-800": "var(--illustration-mint-800)",
        "illustration-mint-700": "var(--illustration-mint-700)",
        "illustration-mint-600": "var(--illustration-mint-600)",
        "illustration-mint-500": "var(--illustration-mint-500)",
        "illustration-mint-400": "var(--illustration-mint-400)",
        "illustration-mint-300": "var(--illustration-mint-300)",
        "illustration-mint-200": "var(--illustration-mint-200)",
        "illustration-mint-100": "var(--illustration-mint-100)",
        "illustration-mint-50": "var(--illustration-mint-50)",
        "illustration-mint-25": "var(--illustration-mint-25)",
        "illustration-aqua-800": "var(--illustration-aqua-800)",
        "illustration-aqua-700": "var(--illustration-aqua-700)",
        "illustration-aqua-600": "var(--illustration-aqua-600)",
        "illustration-aqua-500": "var(--illustration-aqua-500)",
        "illustration-aqua-400": "var(--illustration-aqua-400)",
        "illustration-aqua-300": "var(--illustration-aqua-300)",
        "illustration-aqua-200": "var(--illustration-aqua-200)",
        "illustration-aqua-100": "var(--illustration-aqua-100)",
        "illustration-aqua-50": "var(--illustration-aqua-50)",
        "illustration-aqua-25": "var(--illustration-aqua-25)",
      },
      borderRadius: {
        "radius-rounded": "var(--radius-rounded)",
        "radius-xl": "var(--radius-xl)",
        "radius-l": "var(--radius-l)",
        "radius-m": "var(--radius-m)",
        "radius-s": "var(--radius-s)",
        "radius-xs": "var(--radius-xs)",
        "radius-xxs": "var(--radius-xxs)",
      },
    },
  },
  plugins: [],
};
