export type IAPIRequest =
  | 'LIST_TICKERS'
  | 'SEND_EMAIL_CODE'
  | 'CONNECT_TIDEBIT'
  | 'CONNECT_EMAIL'
  | 'UPDATE_USER_ICON'
  | 'SUBSCRIBE_NEWS_LETTERS'
  | 'LIST_FAVORITE_TICKERS'
  | 'GET_CANDLESTICK_DATA'
  | 'GET_PNL'
  | 'LIST_HISTORIES'
  | 'LIST_DEPOSIT_CRYPTO_CURRENCIES'
  | 'LIST_WITHDRAW_CRYPTO_CURRENCIES'
  | 'LIST_NEWS'
  | 'LIST_COURSES'
  | 'LIST_FAQS'
  | 'LIST_JOBS'
  | 'APPLY_JOB'
  | 'REPORT_ISSUE';
export interface IAPIRequestConstant {
  LIST_TICKERS: IAPIRequest;
  SEND_EMAIL_CODE: IAPIRequest;
  CONNECT_TIDEBIT: IAPIRequest;
  CONNECT_EMAIL: IAPIRequest;
  UPDATE_USER_ICON: IAPIRequest;
  SUBSCRIBE_NEWS_LETTERS: IAPIRequest;
  LIST_FAVORITE_TICKERS: IAPIRequest;
  GET_CANDLESTICK_DATA: IAPIRequest;
  GET_PNL: IAPIRequest;
  LIST_HISTORIES: IAPIRequest;
  LIST_DEPOSIT_CRYPTO_CURRENCIES: IAPIRequest;
  LIST_WITHDRAW_CRYPTO_CURRENCIES: IAPIRequest;
  LIST_NEWS: IAPIRequest;
  LIST_COURSES: IAPIRequest;
  LIST_FAQS: IAPIRequest;
  LIST_JOBS: IAPIRequest;
  APPLY_JOB: IAPIRequest;
  REPORT_ISSUE: IAPIRequest;
}
export const APIRequest: IAPIRequestConstant = {
  LIST_TICKERS: 'LIST_TICKERS',
  SEND_EMAIL_CODE: 'SEND_EMAIL_CODE',
  CONNECT_TIDEBIT: 'CONNECT_TIDEBIT',
  CONNECT_EMAIL: 'CONNECT_EMAIL',
  UPDATE_USER_ICON: 'UPDATE_USER_ICON',
  SUBSCRIBE_NEWS_LETTERS: 'SUBSCRIBE_NEWS_LETTERS',
  LIST_FAVORITE_TICKERS: 'LIST_FAVORITE_TICKERS',
  GET_CANDLESTICK_DATA: 'GET_CANDLESTICK_DATA',
  GET_PNL: 'GET_PNL',
  LIST_HISTORIES: 'LIST_HISTORIES',
  LIST_DEPOSIT_CRYPTO_CURRENCIES: 'LIST_DEPOSIT_CRYPTO_CURRENCIES',
  LIST_WITHDRAW_CRYPTO_CURRENCIES: 'LIST_WITHDRAW_CRYPTO_CURRENCIES',
  LIST_NEWS: 'LIST_NEWS',
  LIST_COURSES: 'LIST_COURSES',
  LIST_FAQS: 'LIST_FAQS',
  LIST_JOBS: 'LIST_JOBS',
  APPLY_JOB: 'APPLY_JOB',
  REPORT_ISSUE: 'REPORT_ISSUE',
};

export type IMethodConstant = 'GET' | 'PUT' | 'DELETE' | 'POST';
export interface IMethod {
  GET: IMethodConstant;
  PUT: IMethodConstant;
  DELETE: IMethodConstant;
  POST: IMethodConstant;
}
export const Method: IMethod = {
  GET: 'GET',
  PUT: 'PUT',
  DELETE: 'DELETE',
  POST: 'POST',
};
