export type ITideBitEvent =
  | 'CONNECTED_WALLET'
  | 'DISCONNECTED_WALLET'
  | 'SERVICE_TERM_ENABLED'
  | 'UPDATE_READ_NOTIFICATIONS'
  | 'UPDATE_READ_NOTIFICATIONS_RESULT'
  | 'BALANCE'
  | 'BALANCES'
  | 'TICKER_CHANGE'
  | 'TICKER'
  | 'TICKER_STATISTIC'
  | 'TICKER_LIVE_STATISTIC'
  | 'CANDLESTICK'
  | 'OPEN_CFD'
  | 'CLOSE_CFD'
  | 'DEPOSIT'
  | 'WITHDRAW';
export interface ITideBitEventConstant {
  CONNECTED_WALLET: ITideBitEvent;
  DISCONNECTED_WALLET: ITideBitEvent;
  SERVICE_TERM_ENABLED: ITideBitEvent;
  UPDATE_READ_NOTIFICATIONS: ITideBitEvent;
  UPDATE_READ_NOTIFICATIONS_RESULT: ITideBitEvent;
  BALANCE: ITideBitEvent;
  BALANCES: ITideBitEvent;
  TICKER: ITideBitEvent;
  TICKER_CHANGE: ITideBitEvent;
  TICKER_STATISTIC: ITideBitEvent;
  TICKER_LIVE_STATISTIC: ITideBitEvent;
  CANDLESTICK: ITideBitEvent;
  OPEN_CFD: ITideBitEvent;
  CLOSE_CFD: ITideBitEvent;
  DEPOSIT: ITideBitEvent;
  WITHDRAW: ITideBitEvent;
}
export const TideBitEvent: ITideBitEventConstant = {
  CONNECTED_WALLET: 'CONNECTED_WALLET',
  DISCONNECTED_WALLET: 'DISCONNECTED_WALLET',
  SERVICE_TERM_ENABLED: 'SERVICE_TERM_ENABLED',
  UPDATE_READ_NOTIFICATIONS: 'UPDATE_READ_NOTIFICATIONS',
  UPDATE_READ_NOTIFICATIONS_RESULT: 'UPDATE_READ_NOTIFICATIONS_RESULT',
  BALANCE: 'BALANCE',
  BALANCES: 'BALANCES',
  TICKER: 'TICKER',
  TICKER_CHANGE: 'TICKER_CHANGE',
  TICKER_STATISTIC: 'TICKER_STATISTIC',
  TICKER_LIVE_STATISTIC: 'TICKER_LIVE_STATISTIC',
  CANDLESTICK: 'CANDLESTICK',
  OPEN_CFD: 'OPEN_CFD',
  CLOSE_CFD: 'CLOSE_CFD',
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
};
